USE RealEstateAgency;

DROP TABLE IF EXISTS Offer;
DROP TABLE IF EXISTS ContractRole;
DROP TABLE IF EXISTS [Contract];
DROP TABLE IF EXISTS Discount;
DROP TABLE IF EXISTS Listing;
DROP TABLE IF EXISTS ListingType;
DROP TABLE IF EXISTS Inspection;
DROP TABLE IF EXISTS Agent;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Property;
DROP VIEW IF EXISTS InspectionsForLostowice;